### ISSUE TITLE
[Feature] Ignore certain words like un di

### ISSUE THREAD

**Issue by TopHatMan** [grncdr/js-capitalize#10]
I wrote this quickly but your welcome to take it or change it.

`const STRING_UP = (string) =>{
  if (typeof string !== 'string')
    return;
  const avoid = ['di','un'];
  let str = string.split(' ');
  let  _s = '';
  let max = str.length -1;
  str.forEach((s,i) =>{
    if(avoid.find((_a) => _a === s)){
      console.log('turd in punchbowl');
      _s += s;
      if(i !== max)
        _s+= ' ';
    }else{
      _s += s.toLowerCase().replace(/(^|[^a-zA-Z\u00C0-\u017F'])([a-zA-Z\u00C0-\u017F])/g, function (m) {
        return m.toUpperCase();
      });
      if(i !== max)
        _s+= ' ';
    }
  });
  return _s;
};
`

**Comment by grncdr** [comment]
Thanks, I think I’ll leave it out for now, but it could be useful as a separate utility.
