### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by dcousens** [grncdr/js-capitalize#4]
You have example tests in the README, but none in the repository?

**Comment by everyonesdesign** [comment]
@dcousens
Actually it uses [markdown-code-blocks](https://www.npmjs.com/package/markdown-code-blocks) to extract tests directly from readme and execute them (see command `"test": "markdown-code-blocks -t javascript < README.md | node"`)

**Comment by dcousens** [comment]
That is awesome, especially for a small module.
